"""Demo AI Mode knowledge: short, general safety answers in four languages, chosen by keyword.

These are deliberately general good practice (no regulation numbers, no phone numbers, no medical advice), so
the assistant can be demonstrated offline without inventing anything. With an API key the live model answers
instead, under the same guardrails.
"""
from app.models.enums import Language

# topic -> keywords in any supported language (lower-case substrings)
TOPIC_KEYWORDS: dict[str, list[str]] = {
    "report": ["report", "how do i tell", "anonymous", "रिपोर्ट", "शिकायत", "बताऊँ", "अहवाल", "कळवू", "melden", "meldung"],
    "ppe": ["ppe", "helmet", "glove", "goggle", "glasses", "mask", "vest", "shoe", "boot", "हेलमेट", "दस्ताने", "मास्क",
            "चश्मा", "जूते", "हातमोजे", "बूट", "psa", "helm", "handschuh", "schutzbrille", "sicherheitsschuh"],
    "lifting": ["lift", "heavy", "carry", "back", "sack", "box", "उठा", "भारी", "कमर", "बोरी", "उचल", "जड", "पाठ",
                "heben", "schwer", "tragen", "rücken"],
    "fire": ["fire", "extinguisher", "smoke", "flammable", "आग", "अग्नि", "धुआँ", "धूर", "अग्निशामक", "feuer", "brand",
             "feuerlöscher"],
    "chemical": ["chemical", "acid", "solvent", "fumes", "gas", "रसायन", "केमिकल", "तेज़ाब", "गैस", "आम्ल", "chemikal",
                 "säure", "lösemittel", "dämpfe"],
    "noise": ["noise", "loud", "ear", "hearing", "शोर", "आवाज़", "कान", "आवाज", "lärm", "laut", "gehör", "ohr"],
    "height": ["ladder", "height", "scaffold", "roof", "harness", "सीढ़ी", "ऊँचाई", "शिडी", "उंची", "leiter", "höhe",
               "gerüst", "absturz"],
    "electrical": ["electric", "wire", "cable", "shock", "socket", "spark", "बिजली", "तार", "करंट", "वीज", "वायर",
                   "strom", "kabel", "elektr", "steckdose"],
    "heat_fatigue": ["heat", "hot", "water", "thirst", "tired", "fatigue", "sleep", "rest", "गर्मी", "प्यास", "थक",
                     "नींद", "उष्ण", "तहान", "थकवा", "झोप", "hitze", "durst", "müde", "pause"],
    "machine": ["machine", "guard", "conveyor", "jam", "lockout", "press", "मशीन", "गार्ड", "कन्वेयर", "यंत्र",
                "maschine", "schutzvorrichtung", "förderband"],
}

ANSWERS: dict[str, dict[Language, list[str]]] = {
    "report": {
        Language.en: ["Reporting takes less than a minute:", "Tap \"Report a hazard\" for something that could hurt someone, or \"Report an incident\" if something already happened.",
                      "Add a photo if you can do it safely.", "For hazards you can tick \"Report anonymously\" and your name won't be stored."],
        Language.hi: ["रिपोर्ट करने में एक मिनट से भी कम लगता है:", "किसी खतरे के लिए \"खतरा बताइए\" दबाइए, और अगर कुछ हो चुका है तो \"घटना बताइए\"।",
                      "अगर सुरक्षित हो तो फ़ोटो जोड़िए।", "खतरे की रिपोर्ट में \"बिना नाम के\" चुन सकते हैं, तब आपका नाम सेव नहीं होगा।"],
        Language.mr: ["अहवाल द्यायला एक मिनिटापेक्षा कमी वेळ लागतो:", "धोक्यासाठी \"धोका कळवा\" दाबा, आणि काही घडले असेल तर \"घटना कळवा\".",
                      "सुरक्षित असेल तर फोटो जोडा.", "धोक्याच्या अहवालात \"नाव न देता\" निवडू शकता, मग तुमचे नाव साठवले जात नाही."],
        Language.de: ["Eine Meldung dauert weniger als eine Minute:", "Tippen Sie auf „Gefahr melden“ für etwas, das jemanden verletzen könnte, oder auf „Vorfall melden“, wenn schon etwas passiert ist.",
                      "Fügen Sie ein Foto hinzu, wenn das gefahrlos möglich ist.", "Gefahren können Sie anonym melden, dann wird Ihr Name nicht gespeichert."],
    },
    "ppe": {
        Language.en: ["Wear the PPE your task needs, every time:", "Check it before you start: no cracks, tears or worn soles.",
                      "Replace anything damaged or past its replacement date. Your dashboard shows what's due.",
                      "If the right PPE isn't available, tell your supervisor before starting the job."],
        Language.hi: ["अपने काम के लिए ज़रूरी सुरक्षा उपकरण हर बार पहनिए:", "काम शुरू करने से पहले जाँचिए: कोई दरार, फटा हिस्सा या घिसा तला न हो।",
                      "खराब या पुराना उपकरण बदलवाइए। आपके डैशबोर्ड पर दिखता है कि क्या बदलना है।",
                      "अगर सही उपकरण नहीं है, तो काम शुरू करने से पहले सुपरवाइज़र को बताइए।"],
        Language.mr: ["कामासाठी लागणारी सुरक्षा साधने प्रत्येक वेळी वापरा:", "काम सुरू करण्याआधी तपासा: तडा, फाटलेला भाग किंवा झिजलेला तळ नको.",
                      "खराब किंवा जुनी साधने बदलून घ्या. काय बदलायचे ते तुमच्या डॅशबोर्डवर दिसते.",
                      "योग्य साधन नसेल तर काम सुरू करण्याआधी सुपरवायझरला सांगा."],
        Language.de: ["Tragen Sie bei jeder Tätigkeit die nötige PSA:", "Vor Arbeitsbeginn prüfen: keine Risse, Löcher oder abgelaufenen Sohlen.",
                      "Beschädigtes oder überfälliges Material austauschen lassen. Ihr Dashboard zeigt, was fällig ist.",
                      "Fehlt die passende PSA, sagen Sie es vor Arbeitsbeginn Ihren Vorgesetzten."],
    },
    "lifting": {
        Language.en: ["To lift safely:", "Test the weight first. If it feels too heavy, use a trolley or lift assist, or get a second person.",
                      "Bend your knees, keep your back straight and hold the load close to your body.",
                      "Don't twist while carrying: turn with your feet. Take short breaks on repetitive lifting."],
        Language.hi: ["सुरक्षित तरीके से उठाने के लिए:", "पहले वज़न जाँचिए। ज़्यादा भारी लगे तो ट्रॉली या मशीन का इस्तेमाल कीजिए, या किसी साथी को बुलाइए।",
                      "घुटने मोड़िए, कमर सीधी रखिए और सामान को शरीर के पास पकड़िए।",
                      "उठाकर चलते समय कमर मत मोड़िए, पैरों से घूमिए। बार-बार उठाने वाले काम में छोटे ब्रेक लीजिए।"],
        Language.mr: ["सुरक्षितपणे उचलण्यासाठी:", "आधी वजन तपासा. जास्त जड वाटले तर ट्रॉली किंवा मशीन वापरा, किंवा सहकाऱ्याला बोलवा.",
                      "गुडघे वाकवा, पाठ सरळ ठेवा आणि सामान शरीराजवळ धरा.",
                      "उचलून चालताना कंबर वळवू नका, पायांनी वळा. सतत उचलण्याच्या कामात छोटे ब्रेक घ्या."],
        Language.de: ["So heben Sie sicher:", "Prüfen Sie zuerst das Gewicht. Ist es zu schwer, nutzen Sie einen Wagen oder eine Hebehilfe oder holen Sie Hilfe.",
                      "In die Knie gehen, Rücken gerade halten und die Last nah am Körper tragen.",
                      "Beim Tragen nicht verdrehen, sondern mit den Füßen drehen. Bei häufigem Heben kurze Pausen machen."],
    },
    "fire": {
        Language.en: ["Fire safety basics:", "Keep exits, fire doors and extinguishers clear at all times.",
                      "Store oily rags and flammable liquids in closed, labelled containers away from heat.",
                      "Know your nearest alarm point and assembly point. Use an extinguisher only if you're trained and the fire is small."],
        Language.hi: ["आग से बचाव की बुनियादी बातें:", "निकास, फ़ायर डोर और आग बुझाने वाले सिलेंडर के सामने कभी सामान मत रखिए।",
                      "तेल वाले कपड़े और जलने वाले तरल ढके, लेबल लगे डिब्बों में, गर्मी से दूर रखिए।",
                      "पास का अलार्म और इकट्ठा होने की जगह याद रखिए। सिलेंडर तभी चलाइए जब ट्रेनिंग हो और आग छोटी हो।"],
        Language.mr: ["आगीपासून सुरक्षिततेच्या मूलभूत गोष्टी:", "बाहेर पडण्याचे मार्ग, फायर डोअर आणि अग्निशामक नेहमी मोकळे ठेवा.",
                      "तेलकट कापडे आणि ज्वलनशील द्रव झाकलेल्या, लेबल असलेल्या डब्यात, उष्णतेपासून दूर ठेवा.",
                      "जवळचा अलार्म आणि जमण्याची जागा लक्षात ठेवा. प्रशिक्षण असेल आणि आग लहान असेल तरच अग्निशामक वापरा."],
        Language.de: ["Grundregeln Brandschutz:", "Ausgänge, Brandschutztüren und Feuerlöscher immer freihalten.",
                      "Ölige Lappen und brennbare Flüssigkeiten in geschlossenen, beschrifteten Behältern fern von Hitze lagern.",
                      "Nächsten Feuermelder und Sammelplatz kennen. Einen Feuerlöscher nur benutzen, wenn Sie geschult sind und das Feuer klein ist."],
    },
    "chemical": {
        Language.en: ["Working with chemicals:", "Read the label and the safety data sheet before you use anything new.",
                      "Wear the gloves and eye protection it asks for, and work where there's good ventilation.",
                      "Never mix chemicals, keep lids closed, and report leaks or strong smells straight away."],
        Language.hi: ["रसायन के साथ काम करते समय:", "कोई नया रसायन इस्तेमाल करने से पहले लेबल और सुरक्षा जानकारी (SDS) पढ़िए।",
                      "उसमें बताए गए दस्ताने और आँखों की सुरक्षा पहनिए, और हवादार जगह पर काम कीजिए।",
                      "रसायन कभी मत मिलाइए, ढक्कन बंद रखिए, और रिसाव या तेज़ गंध तुरंत बताइए।"],
        Language.mr: ["रसायनांसोबत काम करताना:", "नवीन रसायन वापरण्याआधी लेबल आणि सुरक्षा माहिती (SDS) वाचा.",
                      "त्यात सांगितलेले हातमोजे आणि डोळ्यांचे संरक्षण वापरा, आणि हवेशीर जागी काम करा.",
                      "रसायने कधीही मिसळू नका, झाकणे बंद ठेवा, आणि गळती किंवा तीव्र वास लगेच कळवा."],
        Language.de: ["Arbeiten mit Chemikalien:", "Vor dem ersten Einsatz Etikett und Sicherheitsdatenblatt lesen.",
                      "Die dort genannten Handschuhe und den Augenschutz tragen und für gute Lüftung sorgen.",
                      "Chemikalien nie mischen, Behälter geschlossen halten und Lecks oder starken Geruch sofort melden."],
    },
    "noise": {
        Language.en: ["Protecting your hearing:", "Wear ear protection wherever the signs say so, for the whole time you're there.",
                      "A simple check: if you have to shout to someone an arm's length away, it's too loud without protection.",
                      "Report empty ear-plug dispensers or very loud machines so they can be fixed."],
        Language.hi: ["कानों की सुरक्षा:", "जहाँ बोर्ड लगा हो वहाँ पूरे समय कान की सुरक्षा पहनिए।",
                      "आसान जाँच: अगर हाथ भर दूर खड़े व्यक्ति से चिल्लाकर बात करनी पड़े, तो बिना सुरक्षा के शोर बहुत ज़्यादा है।",
                      "ईयरप्लग खत्म हों या कोई मशीन बहुत तेज़ हो, तो रिपोर्ट कीजिए।"],
        Language.mr: ["कानांचे संरक्षण:", "जिथे फलक लावला आहे तिथे संपूर्ण वेळ कानांचे संरक्षण वापरा.",
                      "सोपी तपासणी: हाताच्या अंतरावरच्या व्यक्तीशी ओरडून बोलावे लागत असेल, तर संरक्षणाशिवाय आवाज खूप जास्त आहे.",
                      "इअरप्लग संपले असतील किंवा मशीन खूप मोठा आवाज करत असेल तर कळवा."],
        Language.de: ["Gehörschutz:", "Tragen Sie Gehörschutz überall dort, wo Schilder es verlangen, und zwar die ganze Zeit.",
                      "Einfacher Test: Wenn Sie jemanden auf Armlänge anschreien müssen, ist es ohne Schutz zu laut.",
                      "Melden Sie leere Gehörschutzspender oder sehr laute Maschinen."],
    },
    "height": {
        Language.en: ["Working at height:", "Check the ladder before use and stand it on firm, level ground.",
                      "Keep three points of contact and don't lean or overreach. Move the ladder instead.",
                      "Use a platform or harness where your task requires it, and never work at height alone if you feel unwell."],
        Language.hi: ["ऊँचाई पर काम करते समय:", "इस्तेमाल से पहले सीढ़ी जाँचिए और उसे मज़बूत, समतल ज़मीन पर रखिए।",
                      "तीन जगह से पकड़ बनाए रखिए और ज़्यादा झुकिए मत। सीढ़ी खिसकाइए।",
                      "जहाँ ज़रूरी हो वहाँ प्लेटफ़ॉर्म या हार्नेस इस्तेमाल कीजिए, और तबियत ठीक न हो तो ऊँचाई पर काम मत कीजिए।"],
        Language.mr: ["उंचीवर काम करताना:", "वापरण्याआधी शिडी तपासा आणि ती घट्ट, सपाट जमिनीवर ठेवा.",
                      "तीन ठिकाणी पकड ठेवा आणि जास्त वाकू नका. त्याऐवजी शिडी सरकवा.",
                      "आवश्यक तिथे प्लॅटफॉर्म किंवा हार्नेस वापरा, आणि बरे वाटत नसेल तर उंचीवर काम करू नका."],
        Language.de: ["Arbeiten in der Höhe:", "Leiter vor der Benutzung prüfen und auf festen, ebenen Boden stellen.",
                      "Immer drei Kontaktpunkte halten und sich nicht weit hinauslehnen. Lieber die Leiter umstellen.",
                      "Wo nötig eine Plattform oder einen Auffanggurt verwenden, und nicht in der Höhe arbeiten, wenn Sie sich unwohl fühlen."],
    },
    "electrical": {
        Language.en: ["Electrical safety:", "Don't touch damaged cables, cracked sockets or anything that sparks. Report it straight away.",
                      "Only qualified people should open panels or repair equipment, and only after it is locked off.",
                      "Keep water and liquids away from electrical equipment."],
        Language.hi: ["बिजली से सुरक्षा:", "कटे तार, टूटे सॉकेट या चिंगारी देने वाली चीज़ को मत छूइए। तुरंत रिपोर्ट कीजिए।",
                      "पैनल खोलना या मरम्मत सिर्फ़ योग्य व्यक्ति करे, और वह भी बिजली बंद और लॉक करने के बाद।",
                      "पानी और तरल चीज़ें बिजली के उपकरणों से दूर रखिए।"],
        Language.mr: ["विजेपासून सुरक्षा:", "तुटलेल्या वायर, फुटलेले सॉकेट किंवा ठिणग्या देणाऱ्या वस्तूला हात लावू नका. लगेच कळवा.",
                      "पॅनल उघडणे किंवा दुरुस्ती फक्त पात्र व्यक्तीनेच, वीज बंद व लॉक केल्यानंतरच करावी.",
                      "पाणी आणि द्रव पदार्थ विजेच्या उपकरणांपासून दूर ठेवा."],
        Language.de: ["Elektrische Sicherheit:", "Beschädigte Kabel, gebrochene Steckdosen oder Funken nicht berühren und sofort melden.",
                      "Nur Fachkräfte dürfen Schaltschränke öffnen oder Geräte reparieren, und erst nach dem Freischalten.",
                      "Wasser und Flüssigkeiten von elektrischen Geräten fernhalten."],
    },
    "heat_fatigue": {
        Language.en: ["Heat and tiredness:", "Drink water regularly, before you feel thirsty, and take breaks in the shade or a cool area.",
                      "Tiredness causes accidents. Tell your supervisor if you're very tired, dizzy or unwell.",
                      "Swap heavy and light tasks during the shift when you can."],
        Language.hi: ["गर्मी और थकान:", "प्यास लगने से पहले ही थोड़ी-थोड़ी देर में पानी पीते रहिए, और छाँव या ठंडी जगह पर ब्रेक लीजिए।",
                      "थकान से दुर्घटनाएँ होती हैं। बहुत थकान, चक्कर या तबियत खराब लगे तो सुपरवाइज़र को बताइए।",
                      "जहाँ हो सके, शिफ़्ट में भारी और हल्के काम बदलते रहिए।"],
        Language.mr: ["उष्णता आणि थकवा:", "तहान लागण्याआधीच थोड्या थोड्या वेळाने पाणी प्या, आणि सावलीत किंवा थंड जागी ब्रेक घ्या.",
                      "थकव्यामुळे अपघात होतात. खूप थकवा, चक्कर किंवा बरे वाटत नसेल तर सुपरवायझरला सांगा.",
                      "शक्य असेल तर शिफ्टमध्ये जड आणि हलकी कामे आलटून पालटून करा."],
        Language.de: ["Hitze und Müdigkeit:", "Regelmäßig Wasser trinken, schon bevor Sie Durst haben, und Pausen im Schatten oder Kühlen machen.",
                      "Müdigkeit verursacht Unfälle. Sagen Sie Ihren Vorgesetzten, wenn Sie sehr müde, schwindelig oder unwohl sind.",
                      "Wenn möglich, schwere und leichte Aufgaben während der Schicht abwechseln."],
    },
    "machine": {
        Language.en: ["Machine safety:", "Never remove or bypass a guard or interlock, even for a moment.",
                      "Stop the machine and lock it off before clearing a jam or cleaning it.",
                      "Keep loose clothing, hair and jewellery away from moving parts."],
        Language.hi: ["मशीन से सुरक्षा:", "गार्ड या इंटरलॉक को कभी मत हटाइए या बायपास कीजिए, एक पल के लिए भी नहीं।",
                      "फँसा माल निकालने या सफ़ाई से पहले मशीन बंद करके लॉक कीजिए।",
                      "ढीले कपड़े, बाल और गहने चलते हिस्सों से दूर रखिए।"],
        Language.mr: ["मशीनपासून सुरक्षा:", "गार्ड किंवा इंटरलॉक कधीही काढू नका किंवा बायपास करू नका, एका क्षणासाठीही नाही.",
                      "अडकलेला माल काढण्याआधी किंवा साफसफाईआधी मशीन बंद करून लॉक करा.",
                      "सैल कपडे, केस आणि दागिने फिरणाऱ्या भागांपासून दूर ठेवा."],
        Language.de: ["Maschinensicherheit:", "Schutzvorrichtungen oder Verriegelungen nie entfernen oder überbrücken, auch nicht kurz.",
                      "Maschine vor dem Beseitigen einer Störung oder dem Reinigen stoppen und sichern.",
                      "Lose Kleidung, Haare und Schmuck von beweglichen Teilen fernhalten."],
    },
    "fallback": {
        Language.en: ["I can help with general safety questions about:",
                      "PPE, safe lifting, fire, chemicals, noise, ladders and height, electricity, heat and tiredness, machines, and how to report something.",
                      "Ask me in your own words. If you can see something unsafe right now, report it so your supervisor can act."],
        Language.hi: ["मैं इन विषयों पर सामान्य सुरक्षा सवालों में मदद कर सकता हूँ:",
                      "सुरक्षा उपकरण, सही तरीके से उठाना, आग, रसायन, शोर, सीढ़ी और ऊँचाई, बिजली, गर्मी और थकान, मशीनें, और रिपोर्ट कैसे करें।",
                      "अपने शब्दों में पूछिए। अगर अभी कुछ असुरक्षित दिख रहा है, तो उसकी रिपोर्ट कीजिए ताकि सुपरवाइज़र कदम उठा सके।"],
        Language.mr: ["मी या विषयांवरील सामान्य सुरक्षा प्रश्नांमध्ये मदत करू शकतो:",
                      "सुरक्षा साधने, योग्य पद्धतीने उचलणे, आग, रसायने, आवाज, शिडी आणि उंची, वीज, उष्णता आणि थकवा, मशीन, आणि अहवाल कसा द्यायचा.",
                      "तुमच्या शब्दांत विचारा. आत्ता काही असुरक्षित दिसत असेल तर कळवा, म्हणजे सुपरवायझर पावले उचलू शकतील."],
        Language.de: ["Ich helfe bei allgemeinen Sicherheitsfragen zu:",
                      "PSA, sicherem Heben, Brandschutz, Chemikalien, Lärm, Leitern und Höhe, Elektrizität, Hitze und Müdigkeit, Maschinen und dazu, wie man etwas meldet.",
                      "Fragen Sie in Ihren eigenen Worten. Wenn Sie gerade etwas Unsicheres sehen, melden Sie es, damit gehandelt werden kann."],
    },
}


def topic_for(text: str) -> str:
    low = text.lower()
    scores = {topic: sum(k in low for k in words) for topic, words in TOPIC_KEYWORDS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] else "fallback"


def answer(topic: str, lang: Language) -> str:
    lines = ANSWERS[topic].get(lang) or ANSWERS[topic][Language.en]
    return lines[0] + "\n" + "\n".join(f"• {line}" for line in lines[1:])
