"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 07:29:38.772547
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('ppe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('replacement_interval_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ppe_items')),
    sa.UniqueConstraint('name', name=op.f('uq_ppe_items_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('worker', 'supervisor', 'admin', name='rolename_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('training_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('pass_mark', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_courses'))
    )
    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_courses_category'), ['category'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_locations_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_department_id'), ['department_id'], unique=False)

    op.create_table('safety_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_safety_checklists_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_checklists'))
    )
    with op.batch_alter_table('safety_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_checklists_department_id'), ['department_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'hi', 'mr', 'de', name='language_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistant', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('checklist_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['safety_checklists.id'], name=op.f('fk_checklist_results_checklist_id_safety_checklists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_checklist_results_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checklist_results_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_results'))
    )
    with op.batch_alter_table('checklist_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_results_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_results_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_results_failed_items'), ['failed_items'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_results_user_id'), ['user_id'], unique=False)

    op.create_table('drudgery_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('interventions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_drudgery_assessments_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drudgery_assessments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drudgery_assessments'))
    )
    with op.batch_alter_table('drudgery_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drudgery_assessments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drudgery_assessments_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_drudgery_assessments_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_drudgery_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('ergonomic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'moderate', 'high', 'critical', name='risklevel_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ergonomic_assessments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ergonomic_assessments'))
    )
    with op.batch_alter_table('ergonomic_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ergonomic_assessments_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_ergonomic_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('unsafe_machine', 'slippery_floor', 'exposed_wire', 'missing_ppe', 'excessive_noise', 'poor_lighting', 'chemical_leak', 'unsafe_lifting', 'fire_hazard', 'blocked_exit', 'ergonomic', 'other', name='hazardcategory_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_language', sa.Enum('en', 'hi', 'mr', 'de', name='language_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'controlled', 'closed', name='hazardstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_hazards_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_hazards_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_hazards_reporter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hazards')),
    sa.UniqueConstraint('reference', name=op.f('uq_hazards_reference'))
    )
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazards_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_status'), ['status'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_language', sa.Enum('en', 'hi', 'mr', 'de', name='language_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('people_involved', sa.String(length=500), nullable=True),
    sa.Column('injury_occurred', sa.Boolean(), nullable=False),
    sa.Column('injury_details', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('reported', 'assigned', 'investigating', 'corrective_action', 'verification', 'closed', name='incidentstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_incidents_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], name=op.f('fk_incidents_investigator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_incidents_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_incidents_reporter_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('reference', name=op.f('uq_incidents_reference'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_category'), ['category'], unique=False)
        batch_op.create_index('ix_incidents_dept_occurred', ['department_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_investigator_id'), ['investigator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_knowledge_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_knowledge_documents_storage_key'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.Enum('info', 'warning', 'critical', name='notificationpriority_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('certified_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], name=op.f('fk_training_progress_course_id_training_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_progress')),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_training_progress_user_course')
    )
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_progress_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_progress_user_id'), ['user_id'], unique=False)

    op.create_table('training_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], name=op.f('fk_training_quizzes_course_id_training_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_training_quizzes_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_quizzes'))
    )
    with op.batch_alter_table('training_quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_quizzes_course_id'), ['course_id'], unique=False)

    op.create_table('wellbeing_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('feeling', sa.String(length=16), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('physical_fatigue', sa.Integer(), nullable=False),
    sa.Column('mental_workload', sa.Integer(), nullable=False),
    sa.Column('support_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wellbeing_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellbeing_checkins'))
    )
    with op.batch_alter_table('wellbeing_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wellbeing_checkins_checkin_date'), ['checkin_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wellbeing_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('worker_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_category', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_worker_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_feedback'))
    )
    with op.batch_alter_table('worker_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_feedback_ai_category'), ['ai_category'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('shift', sa.Enum('morning', 'evening', 'night', name='shift_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('primary_location_id', sa.Integer(), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_location_id'], ['locations.id'], name=op.f('fk_workers_primary_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('fk_workers_supervisor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_workers_user_id'))
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_supervisor_id'), ['supervisor_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=24), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('hazard_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], name=op.f('fk_attachments_hazard_id_hazards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_attachments_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attachments_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_attachments_storage_key'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_hazard_id'), ['hazard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_incident_id'), ['incident_id'], unique=False)

    op.create_table('corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('hazard_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_level', sa.Enum('elimination', 'substitution', 'engineering', 'administrative', 'ppe', name='controllevel_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='actionstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], name=op.f('fk_corrective_actions_hazard_id_hazards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_corrective_actions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], name=op.f('fk_corrective_actions_responsible_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_actions'))
    )
    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrective_actions_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_actions_hazard_id'), ['hazard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_actions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_actions_responsible_id'), ['responsible_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrective_actions_status'), ['status'], unique=False)

    op.create_table('emergency_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emergency_type', sa.Enum('fire', 'medical', 'chemical_spill', 'machinery', 'electrical', 'other', name='emergencytype_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_emergency_events_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_emergency_events_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_emergency_events_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_events'))
    )
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_events_user_id'), ['user_id'], unique=False)

    op.create_table('ppe_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('ppe_item_id', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('replace_by', sa.Date(), nullable=False),
    sa.Column('inspection_status', sa.String(length=24), nullable=False),
    sa.Column('last_inspected_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ppe_item_id'], ['ppe_items.id'], name=op.f('fk_ppe_assignments_ppe_item_id_ppe_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_ppe_assignments_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ppe_assignments')),
    sa.UniqueConstraint('worker_id', 'ppe_item_id', name='uq_ppe_assignment_worker_item')
    )
    with op.batch_alter_table('ppe_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppe_assignments_ppe_item_id'), ['ppe_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppe_assignments_replace_by'), ['replace_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppe_assignments_worker_id'), ['worker_id'], unique=False)

    op.create_table('preventive_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('hazard_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_level', sa.Enum('elimination', 'substitution', 'engineering', 'administrative', 'ppe', name='controllevel_enum', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='actionstatus_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], name=op.f('fk_preventive_actions_hazard_id_hazards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_preventive_actions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], name=op.f('fk_preventive_actions_responsible_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preventive_actions'))
    )
    with op.batch_alter_table('preventive_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preventive_actions_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_actions_hazard_id'), ['hazard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_actions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_actions_responsible_id'), ['responsible_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_actions_status'), ['status'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['training_quizzes.id'], name=op.f('fk_quiz_attempts_quiz_id_training_quizzes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['training_quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_training_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hazard_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'moderate', 'high', 'critical', name='risklevel_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('affected_workers', sa.Integer(), nullable=False),
    sa.Column('exposure_frequency', sa.String(length=64), nullable=True),
    sa.Column('existing_controls', sa.Text(), nullable=True),
    sa.Column('recommended_controls', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('fk_risk_assessments_assessed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], name=op.f('fk_risk_assessments_hazard_id_hazards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_hazard_id'), ['hazard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_risk_score'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_risk_level'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_hazard_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('preventive_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preventive_actions_status'))
        batch_op.drop_index(batch_op.f('ix_preventive_actions_responsible_id'))
        batch_op.drop_index(batch_op.f('ix_preventive_actions_incident_id'))
        batch_op.drop_index(batch_op.f('ix_preventive_actions_hazard_id'))
        batch_op.drop_index(batch_op.f('ix_preventive_actions_due_date'))

    op.drop_table('preventive_actions')
    with op.batch_alter_table('ppe_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppe_assignments_worker_id'))
        batch_op.drop_index(batch_op.f('ix_ppe_assignments_replace_by'))
        batch_op.drop_index(batch_op.f('ix_ppe_assignments_ppe_item_id'))

    op.drop_table('ppe_assignments')
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_events_user_id'))

    op.drop_table('emergency_events')
    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrective_actions_status'))
        batch_op.drop_index(batch_op.f('ix_corrective_actions_responsible_id'))
        batch_op.drop_index(batch_op.f('ix_corrective_actions_incident_id'))
        batch_op.drop_index(batch_op.f('ix_corrective_actions_hazard_id'))
        batch_op.drop_index(batch_op.f('ix_corrective_actions_due_date'))

    op.drop_table('corrective_actions')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_incident_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_hazard_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_supervisor_id'))

    op.drop_table('workers')
    with op.batch_alter_table('worker_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_feedback_ai_category'))

    op.drop_table('worker_feedback')
    with op.batch_alter_table('wellbeing_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wellbeing_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_wellbeing_checkins_checkin_date'))

    op.drop_table('wellbeing_checkins')
    with op.batch_alter_table('training_quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_quizzes_course_id'))

    op.drop_table('training_quizzes')
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_progress_expires_on'))
        batch_op.drop_index(batch_op.f('ix_training_progress_course_id'))

    op.drop_table('training_progress')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))

    op.drop_table('notifications')
    op.drop_table('knowledge_documents')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_location_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_investigator_id'))
        batch_op.drop_index('ix_incidents_dept_occurred')
        batch_op.drop_index(batch_op.f('ix_incidents_category'))

    op.drop_table('incidents')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazards_status'))
        batch_op.drop_index(batch_op.f('ix_hazards_severity'))
        batch_op.drop_index(batch_op.f('ix_hazards_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_hazards_location_id'))
        batch_op.drop_index(batch_op.f('ix_hazards_department_id'))
        batch_op.drop_index(batch_op.f('ix_hazards_category'))

    op.drop_table('hazards')
    with op.batch_alter_table('ergonomic_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ergonomic_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_ergonomic_assessments_risk_level'))

    op.drop_table('ergonomic_assessments')
    with op.batch_alter_table('drudgery_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drudgery_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_drudgery_assessments_score'))
        batch_op.drop_index(batch_op.f('ix_drudgery_assessments_level'))
        batch_op.drop_index(batch_op.f('ix_drudgery_assessments_department_id'))

    op.drop_table('drudgery_assessments')
    with op.batch_alter_table('checklist_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_results_failed_items'))
        batch_op.drop_index(batch_op.f('ix_checklist_results_completed_at'))
        batch_op.drop_index(batch_op.f('ix_checklist_results_checklist_id'))

    op.drop_table('checklist_results')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))

    op.drop_table('users')
    with op.batch_alter_table('safety_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_checklists_department_id'))

    op.drop_table('safety_checklists')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_department_id'))

    op.drop_table('locations')
    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_courses_category'))

    op.drop_table('training_courses')
    op.drop_table('roles')
    op.drop_table('ppe_items')
    op.drop_table('departments')
    # ### end Alembic commands ###
